from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 592)
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-20, -10, 871, 611))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 237, 206))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame.setPalette(palette)
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 100, 713, 229))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.MatricesGrid = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.MatricesGrid.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.MatricesGrid.setContentsMargins(0, 0, 0, 0)
        self.MatricesGrid.setObjectName("MatricesGrid")
        self.matrixA_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.matrixA_label.setObjectName("matrixA_label")
        self.MatricesGrid.addWidget(self.matrixA_label)
        self.MatrixAGrid = QtWidgets.QGridLayout()
        self.MatrixAGrid.setObjectName("MatrixAGrid")
        self.A00 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A00.setObjectName("A00")
        self.MatrixAGrid.addWidget(self.A00, 0, 0, 1, 1)
        self.A20 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A20.setObjectName("A20")
        self.MatrixAGrid.addWidget(self.A20, 2, 0, 1, 1)
        self.A11 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A11.setObjectName("A11")
        self.MatrixAGrid.addWidget(self.A11, 1, 1, 1, 1)
        self.A12 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A12.setObjectName("A12")
        self.MatrixAGrid.addWidget(self.A12, 1, 2, 1, 1)
        self.A02 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A02.setObjectName("A02")
        self.MatrixAGrid.addWidget(self.A02, 0, 2, 1, 1)

        self.A01 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A01.setObjectName("A01")
        self.MatrixAGrid.addWidget(self.A01, 0, 1, 1, 1)

        self.A21 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A21.setObjectName("A21")
        self.MatrixAGrid.addWidget(self.A21, 2, 1, 1, 1)
        self.A10 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A10.setObjectName("A10")
        self.MatrixAGrid.addWidget(self.A10, 1, 0, 1, 1)
        self.A22 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.A22.setObjectName("A22")
        self.MatrixAGrid.addWidget(self.A22, 2, 2, 1, 1)

        # self.A03 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        # self.A03.setObjectName("A03")
        # self.MatrixAGrid.addWidget(self.A03, 0, 3, 1, 1)

        self.MatricesGrid.addLayout(self.MatrixAGrid)
        self.matrixB_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.matrixB_label.setObjectName("matrixB_label")
        self.MatricesGrid.addWidget(self.matrixB_label)
        self.MatrixB_grid = QtWidgets.QVBoxLayout()
        self.MatrixB_grid.setObjectName("MatrixB_grid")
        self.B0 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.B0.setObjectName("B0")
        self.MatrixB_grid.addWidget(self.B0)
        self.B1 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.B1.setObjectName("B1")
        self.MatrixB_grid.addWidget(self.B1)
        self.B2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.B2.setObjectName("B2")
        self.MatrixB_grid.addWidget(self.B2)
        self.MatricesGrid.addLayout(self.MatrixB_grid)
        self.matrixX_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.matrixX_label.setObjectName("matrixX_label")
        self.MatricesGrid.addWidget(self.matrixX_label)
        self.MatrixX_grid = QtWidgets.QVBoxLayout()
        self.MatrixX_grid.setObjectName("MatrixX_grid")
        self.X0 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.X0.setObjectName("X0")
        self.MatrixX_grid.addWidget(self.X0)
        self.X1 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.X1.setObjectName("X1")
        self.MatrixX_grid.addWidget(self.X1)
        self.X2 = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.X2.setObjectName("X2")
        self.MatrixX_grid.addWidget(self.X2)
        self.MatricesGrid.addLayout(self.MatrixX_grid)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(170, 20, 481, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(150, 350, 481, 141))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.toolsGrid = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.toolsGrid.setContentsMargins(0, 0, 0, 0)
        self.toolsGrid.setObjectName("toolsGrid")
        self.method_combo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.method_combo.setModelColumn(0)
        self.method_combo.setObjectName("method_combo")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.method_combo.addItem("")
        self.toolsGrid.addWidget(self.method_combo, 0, 1, 1, 1)
        self.decomposition_method_combo = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.decomposition_method_combo.setObjectName("decomposition_method_combo")
        self.decomposition_method_combo.addItem("")
        self.decomposition_method_combo.addItem("")
        self.decomposition_method_combo.addItem("")
        self.toolsGrid.addWidget(self.decomposition_method_combo, 4, 1, 1, 1)
        self.iterations_number_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.iterations_number_label.setObjectName("iterations_number_label")
        self.toolsGrid.addWidget(self.iterations_number_label, 5, 0, 1, 1)
        self.methods_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.methods_label.setObjectName("methods_label")
        self.toolsGrid.addWidget(self.methods_label, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.toolsGrid.addWidget(self.label, 6, 0, 1, 1)
        self.paremters_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.paremters_label.setObjectName("paremters_label")
        self.toolsGrid.addWidget(self.paremters_label, 4, 0, 1, 1)
        self.iterations_number = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.iterations_number.setProperty("value", 3)
        self.iterations_number.setObjectName("iterations_number")
        self.toolsGrid.addWidget(self.iterations_number, 5, 1, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.textEdit.setObjectName("textEdit")
        self.toolsGrid.addWidget(self.textEdit, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.toolsGrid.addWidget(self.label_2, 3, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setProperty("value", 3)
        self.spinBox.setObjectName("spinBox")
        self.toolsGrid.addWidget(self.spinBox, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.matrixA_label.setText(_translate("MainWindow", "Coefficient Matrix A :"))
        self.matrixB_label.setText(_translate("MainWindow", "Constant Matrix B :"))
        self.matrixX_label.setText(_translate("MainWindow", "Initial Guess X :"))
        self.label_3.setText(_translate("MainWindow", "Solving System of Linear Equations"))
        self.method_combo.setCurrentText(_translate("MainWindow", "Gauss Elimination"))
        self.method_combo.setItemText(0, _translate("MainWindow", "Gauss Elimination"))
        self.method_combo.setItemText(1, _translate("MainWindow", "Gaus Jordan Elimination using pivoting"))
        self.method_combo.setItemText(2, _translate("MainWindow", "Gauss Jordan"))
        self.method_combo.setItemText(3, _translate("MainWindow", "LU Decompostion"))
        self.method_combo.setItemText(4, _translate("MainWindow", "Gauss Siedel"))
        self.method_combo.setItemText(5, _translate("MainWindow", "Jacobi Iteration"))
        self.decomposition_method_combo.setItemText(0, _translate("MainWindow", "Downlittle Form"))
        self.decomposition_method_combo.setItemText(1, _translate("MainWindow", "Crout Form"))
        self.decomposition_method_combo.setItemText(2, _translate("MainWindow", "Cholesky Form"))
        self.iterations_number_label.setText(_translate("MainWindow", "Number of iterations :"))
        self.methods_label.setText(_translate("MainWindow", "Method :"))
        self.label.setText(_translate("MainWindow", "Absolute Relative Error :"))
        self.paremters_label.setText(_translate("MainWindow", "Method of decomposition :"))
        self.label_2.setText(_translate("MainWindow", "Number of Significant Figures :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
